const planNameMap: Record<string, string> = {
  'Advanced-Protection': 'Advanced Protection',
  'Advanced-Protection-USD': 'Advanced Protection USD',
  'Bring-Your-Own-Device': 'Bring Your Own Device',
  'Bring-Your-Own-Device-USD-Monthly': 'Bring Your Own Device USD Monthly',
  'Bryan-test-Charge': 'Bryan test Charge',
  'Bryan-test-Charge-USD': 'Bryan test Charge USD',
  'Deep-Red-Plan': 'Deep Red Plan',
  'Deep-Red-Plan-USD-Monthly': 'Deep Red Plan USD Monthly',
  'Dragon-XC46BE-100.00': 'Dragon XC46BE $100.00',
  'Everywhere-Unlimited-Residential': 'Everywhere Unlimited Residential',
  'Everywhere-Unlimited-Residential-USD-Monthly': 'Everywhere Unlimited Residential USD Monthly',
  'Everywhere-Unlimited-Travel': 'Everywhere Unlimited Travel',
  'Everywhere-Unlimited-Travel-USD-Monthly': 'Everywhere Unlimited Travel USD Monthly',
  'FlexPay-Air-Monthly-Price-0.00': 'FlexPay Air Monthly Price $0.00',
  'FlexPay-Air-Monthly-Price-000': 'FlexPay Air Monthly Price $0.00 USD Monthly',
  'FlexPay-Air-Monthly-Price-000-USD-Monthly': 'FlexPay Air Monthly Price $0.00 USD Monthly',
  'FlexPay-Air-Monthly-Price-20.00': 'FlexPay Air Monthly Price $20.00',
  'FlexPay-Air-Monthly-Price-2000': 'FlexPay Air Monthly Price $20.00 USD Monthly',
  'FlexPay-Air-Monthly-Price-2000-USD-Monthly': 'FlexPay Air Monthly Price $20.00 USD Monthly',
  'FlexPay-Omen-Monthly-Price-0.00': 'FlexPay Omen Monthly Price $0.00',
  'FlexPay-Omen-Monthly-Price-000': 'FlexPay Omen Monthly Price $0.00 USD Monthly',
  'FlexPay-Omen-Monthly-Price-000-USD-Monthly': 'FlexPay Omen Monthly Price $0.00 USD Monthly',
  'FlexPay-Omen-Monthly-Price-15.00': 'FlexPay Omen Monthly Price $15.00',
  'FlexPay-Omen-Monthly-Price-1500': 'FlexPay Omen Monthly Price $15.00 USD Monthly',
  'FlexPay-Omen-Monthly-Price-1500-USD-Monthly': 'FlexPay Omen Monthly Price $15.00 USD Monthly',
  'FlexPay-Raptor-Monthly-Price-0.00': 'FlexPay Raptor Monthly Price $0.00',
  'FlexPay-Raptor-Monthly-Price-000': 'FlexPay Raptor Monthly Price $0.00 USD Monthly',
  'FlexPay-Raptor-Monthly-Price-000-USD-Monthly': 'FlexPay Raptor Monthly Price $0.00 USD Monthly',
  'FlexPay-Raptor-Monthly-Price-25.00': 'FlexPay Raptor Monthly Price $25.00',
  'FlexPay-Raptor-Monthly-Price-2500': 'FlexPay Raptor Monthly Price $25.00 USD Monthly',
  'FlexPay-Raptor-Monthly-Price-2500-USD-Monthly': 'FlexPay Raptor Monthly Price $25.00 USD Monthly',
  'Influencer-Kit-Program': 'Influencer Kit Program',
  'Influencer-Kit-Program-USD-Monthly': 'Influencer Kit Program USD Monthly',
  'Late-Fee': 'Late Fee',
  'legendary-charge': 'Legendary Charge',
  'legendary-charge-usd': 'Legendary Charge USD',
  'Modem-Return': 'Modem Return',
  'Modem-Return-USD-Monthly': 'Modem Return USD Monthly',
  'Nomad-300GB-Rural-Plan': 'Nomad 300GB Rural Plan',
  'Nomad-300GB-Rural-Plan-USD-Monthly': 'Nomad 300GB Rural Plan USD Monthly',
  'Nomad-Air-Modem-Basic-Rental-0.50': 'Nomad Air Modem Basic Rental $0.50',
  'Nomad-Air-Modem-Basic-Rental-050': 'Nomad Air Modem Basic Rental $0.50 USD Monthly',
  'Nomad-Air-Modem-Basic-Rental-050-USD-Monthly': 'Nomad Air Modem Basic Rental $0.50 USD Monthly',
  'Nomad-Air-Modem-Basic-Rental-10.00': 'Nomad Air Modem Basic Rental $10.00',
  'Nomad-Air-Modem-Basic-Rental-1000': 'Nomad Air Modem Basic Rental $10.00 USD Monthly',
  'Nomad-Air-Modem-Basic-Rental-1000-USD-Monthly': 'Nomad Air Modem Basic Rental $10.00 USD Monthly',
  'Nomad-Air-Modem-Premier-Rental-15.00': 'Nomad Air Modem Premier Rental $15.00',
  'Nomad-Air-Modem-Premier-Rental-1500': 'Nomad Air Modem Premier Rental $15.00 USD Monthly',
  'Nomad-Air-Modem-Premier-Rental-1500-USD-Monthly': 'Nomad Air Modem Premier Rental $15.00 USD Monthly',
  'Nomad-Air-Modem-Premier-Rental-20.00': 'Nomad Air Modem Premier Rental $20.00',
  'Nomad-Air-Modem-Premier-Rental-2000': 'Nomad Air Modem Premier Rental $20.00 USD Monthly',
  'Nomad-Air-Modem-Premier-Rental-2000-USD-Monthly': 'Nomad Air Modem Premier Rental $20.00 USD Monthly',
  'Nomad-Air-One-Time-Basic-0.00': 'Nomad Air One Time Basic $0.00',
  'Nomad-Air-One-Time-Basic-000': 'Nomad Air One Time Basic $0.00 USD Monthly',
  'Nomad-Air-One-Time-Basic-000-USD-Monthly': 'Nomad Air One Time Basic $0.00 USD Monthly',
  'Nomad-Air-One-Time-Premier-0.00': 'Nomad Air One Time Premier $0.00',
  'Nomad-Air-One-Time-Premier-000': 'Nomad Air One Time Premier $0.00 USD Monthly',
  'Nomad-Air-One-Time-Premier-000-USD-Monthly': 'Nomad Air One Time Premier $0.00 USD Monthly',
  'Nomad-Annual-Rural-5G': 'Nomad Annual Rural 5G',
  'Nomad-Annual-Rural-5G-USD-Yearly': 'Nomad Annual Rural 5G USD Yearly',
  'Nomad-Business': 'Nomad Business',
  'Nomad-Business-Internet-200-Annual': 'Nomad Business Internet 200 Annual',
  'Nomad-Business-Internet-200-Annual-USD-Yearly': 'Nomad Business Internet 200 Annual USD Yearly',
  'Nomad-Business-Modem-Rental-15.00': 'Nomad Business Modem Rental $15.00',
  'Nomad-Business-Modem-Rental-1500': 'Nomad Business Modem Rental $15.00 USD Monthly',
  'Nomad-Business-Modem-Rental-1500-USD-Monthly': 'Nomad Business Modem Rental $15.00 USD Monthly',
  'Nomad-Business-Modem-Rental-with-Nomad-Premier-25.00': 'Nomad Business Modem Rental with Nomad Premier $25.00',
  'Nomad-Business-Modem-Rental-with-Nomad-Premier-2500': 'Nomad Business Modem Rental with Nomad Premier $25.00 USD Monthly',
  'Nomad-Business-Modem-Rental-with-Nomad-Premier-2500-USD-Monthly': 'Nomad Business Modem Rental with Nomad Premier $25.00 USD Monthly',
  'Nomad-Business-USD-Monthly': 'Nomad Business USD Monthly',
  'Nomad-Cube-Plan': 'Nomad Cube Plan',
  'Nomad-Cube-Plan-USD-Monthly': 'Nomad Cube Plan USD Monthly',
  'Nomad-Dragon': 'Nomad Dragon',
  'Nomad-Dragon-0': 'Nomad Dragon 0',
  'Nomad-Dragon-0-USD-Monthly': 'Nomad Dragon 0 USD Monthly',
  'Nomad-Dragon-Modem-Basic-Rental-10.00': 'Nomad Dragon Modem Basic Rental $10.00',
  'Nomad-Dragon-Modem-Basic-Rental-1000': 'Nomad Dragon Modem Basic Rental $10.00 USD Monthly',
  'Nomad-Dragon-Modem-Basic-Rental-1000-USD-Monthly': 'Nomad Dragon Modem Basic Rental $10.00 USD Monthly',
  'Nomad-Dragon-One-Time-Basic-0.00': 'Nomad Dragon One Time Basic $0.00',
  'Nomad-Dragon-One-Time-Basic-000': 'Nomad Dragon One Time Basic $0.00 USD Monthly',
  'Nomad-Dragon-One-Time-Basic-000-USD-Monthly': 'Nomad Dragon One Time Basic $0.00 USD Monthly',
  'Nomad-Dragon-One-Time-Premier-0.00': 'Nomad Dragon One Time Premier $0.00',
  'Nomad-Dragon-One-Time-Premier-000': 'Nomad Dragon One Time Premier $0.00 USD Monthly',
  'Nomad-Dragon-One-Time-Premier-000-USD-Monthly': 'Nomad Dragon One Time Premier $0.00 USD Monthly',
  'Nomad-Dragon-Service': 'Nomad Unlimited Lite Plan $29.95 First Month + $10 Gift Card',
  'Nomad-Dragon-Service-Plan': 'Nomad Dragon Service Plan',
  'Nomad-Dragon-Service-Plan-USD-Monthly': 'Nomad Dragon Service Plan USD Monthly',
  'Nomad-Dragon-Service-USD-Monthly': 'Nomad Dragon Service Promo Plan',
  'Nomad-Home-Modem-Basic-Rental-0.50': 'Nomad Home Modem Basic Rental $0.50',
  'Nomad-Home-Modem-Basic-Rental-050': 'Nomad Home Modem Basic Rental $0.50 USD Monthly',
  'Nomad-Home-Modem-Basic-Rental-050-USD-Monthly': 'Nomad Home Modem Basic Rental $0.50 USD Monthly',
  'Nomad-Home-Modem-Basic-Rental-5.00': 'Nomad Home Modem Basic Rental $5.00',
  'Nomad-Home-Modem-Basic-Rental-500': 'Nomad Home Modem Basic Rental $5.00 USD Monthly',
  'Nomad-Home-Modem-Basic-Rental-500-USD-Monthly': 'Nomad Home Modem Basic Rental $5.00 USD Monthly',
  'Nomad-Home-Modem-Premier-Rental-10.00': 'Nomad Home Modem Premier Rental $10.00',
  'Nomad-Home-Modem-Premier-Rental-1000': 'Nomad Home Modem Premier Rental $10.00 USD Monthly',
  'Nomad-Home-Modem-Premier-Rental-1000-USD-Monthly': 'Nomad Home Modem Premier Rental $10.00 USD Monthly',
  'Nomad-Home-Modem-Premier-Rental-15.00': 'Nomad Home Modem Premier Rental $15.00',
  'Nomad-Home-Modem-Premier-Rental-1500': 'Nomad Home Modem Premier Rental $15.00 USD Monthly',
  'Nomad-Home-Modem-Premier-Rental-1500-USD-Monthly': 'Nomad Home Modem Premier Rental $15.00 USD Monthly',
  'Nomad-Home-Modem-Rental-15.00': 'Nomad Home Modem Rental $15.00',
  'Nomad-Home-Modem-Rental-1500': 'Nomad Home Modem Rental $15.00 USD Monthly',
  'Nomad-Home-Modem-Rental-1500-USD-Monthly': 'Nomad Home Modem Rental $15.00 USD Monthly',
  'Nomad-Home-Modem-Rental-with-Nomad-Premier-25.00': 'Nomad Home Modem Rental with Nomad Premier $25.00',
  'Nomad-Home-Modem-Rental-with-Nomad-Premier-2500': 'Nomad Home Modem Rental with Nomad Premier $25.00 USD Monthly',
  'Nomad-Home-Modem-Rental-with-Nomad-Premier-2500-USD-Monthly': 'Nomad Home Modem Rental with Nomad Premier $25.00 USD Monthly',
  'Nomad-Home-One-Time-Basic-0.00': 'Nomad Home One Time Basic $0.00',
  'Nomad-Home-One-Time-Basic-000': 'Nomad Home One Time Basic $0.00 USD Monthly',
  'Nomad-Home-One-Time-Basic-000-USD-Monthly': 'Nomad Home One Time Basic $0.00 USD Monthly',
  'Nomad-Home-One-Time-Premier-0.00': 'Nomad Home One Time Premier $0.00',
  'Nomad-Home-One-Time-Premier-000': 'Nomad Home One Time Premier $0.00 USD Monthly',
  'Nomad-Home-One-Time-Premier-000-USD-Monthly': 'Nomad Home One Time Premier $0.00 USD Monthly',
  'Nomad-Internet-Travel-Yearly-828': 'Nomad Internet Travel Yearly $828',
  'Nomad-Internet-Travel-Yearly-828-USD-Yearly': 'Nomad Internet Travel Yearly $828 USD Yearly',
  'Nomad-Internet-Unlimited-5G-PLUS-Plan': 'Nomad Internet Unlimited 5G PLUS Plan 99',
  'Nomad-Internet-Unlimited-5G-PLUS-Plan-149': 'Nomad Internet Unlimited 5G PLUS Plan 149',
  'Nomad-Internet-Unlimited-5G-PLUS-Plan-149-USD-Monthly': 'Nomad Internet Unlimited 5G PLUS Plan 149 USD Monthly',
  'Nomad-Internet-Unlimited-5G-PLUS-Plan-99': 'Nomad Internet Unlimited 5G PLUS Plan 99 USD Monthly',
  'Nomad-Internet-Unlimited-5G-PLUS-Plan-99-USD-Monthly': 'Nomad Internet Unlimited 5G PLUS Plan 99 USD Monthly',
  'Nomad-Internet-Unlimited-5G-PRIME-Plan': 'Nomad Internet Unlimited 5G PRIME Plan',
  'Nomad-Internet-Unlimited-5G-PRIME-Plan-USD-Monthly': 'Nomad Internet Unlimited 5G PRIME Plan USD Monthly',
  'Nomad-Mini--Modem-Kit': 'Nomad Mini-Modem Kit  - One time Rental',
  'Nomad-Mini--Modem-Kit-USD': 'Nomad Mini-Modem Kit USD  - One time Rental',
  'Nomad-Mini-Kit': 'Nomad Mini Kit',
  'Nomad-Mini-Kit-USD': 'Mini Modem Kit',
  'Nomad-Modem-Rental-0.00': 'Nomad Modem Rental $0.00',
  'Nomad-Modem-Rental-000': 'Nomad Modem Rental $0.00 USD Monthly',
  'Nomad-Modem-Rental-000-USD-Monthly': 'Nomad Modem Rental $0.00 USD Monthly',
  'Nomad-Modem-Replacement-Fee': 'Nomad Modem Replacement Fee',
  'Nomad-Modem-Replacement-Fee-USD': 'Nomad Modem Replacement Fee USD',
  'Nomad-Oasis-Upgrade-Full': 'Nomad Oasis Upgrade Full',
  'Nomad-Oasis-Upgrade-Full-USD-Monthly': 'Nomad Oasis Upgrade Full USD Monthly',
  'Nomad-Oasis-Upgrade-Upfront-Paid': 'Nomad Oasis Upgrade Upfront Paid',
  'Nomad-One-Time-Modem-Fee': 'Nomad One Time Modem Fee',
  'Nomad-One-Time-Modem-Fee-USD': 'Nomad One Time Modem Fee USD',
  'Nomad-Power-Plan-Promotional-First-Month': 'Nomad Power Plan Promotional First Month',
  'Nomad-Power-Plan-Promotional-First-Month-USD-Monthly': 'Nomad Power Plan Promotional First Month USD Monthly',
  'Nomad-Prime-10': 'Nomad Prime $10',
  'Nomad-Prime-10-USD-Monthly': 'Nomad Prime $10 USD Monthly',
  'Nomad-Prime-Founders-Plan': 'Nomad Prime Founders Plan',
  'Nomad-Prime-Founders-Plan-USD-Monthly': 'Nomad Prime Founders Plan USD Monthly',
  'Nomad-Prime-Full': 'Nomad Prime 9.95',
  'Nomad-Prime-Full-USD-Monthly': 'Nomad Prime Full USD Monthly',
  'Nomad-Prime-Oasis-Upgrade': 'Nomad Prime + Oasis Upgrade',
  'Nomad-Prime-Oasis-Upgrade-USD-Monthly': 'Nomad Prime + Oasis Upgrade USD Monthly',
  'Nomad-Prime-Oasis-Upgrade-USD-Yearly': 'Nomad Prime + Oasis Upgrade USD Yearly',
  'Nomad-Prime-Upgrade-10.00': 'Nomad Prime Upgrade $10.00',
  'Nomad-Prime-Upgrade-1000': 'Nomad Prime Upgrade $10.00 USD Monthly',
  'Nomad-Prime-Upgrade-1000-USD-Monthly': 'Nomad Prime Upgrade $10.00 USD Monthly',
  'Nomad-Raptor-Modem-Basic-Rental-0.00': 'Nomad Raptor Modem Basic Rental $0.00',
  'Nomad-Raptor-Modem-Basic-Rental-000': 'Nomad Raptor Modem Basic Rental $0.00 USD Monthly',
  'Nomad-Raptor-Modem-Basic-Rental-000-USD-Monthly': 'Nomad Raptor Modem Basic Rental $0.00 USD Monthly',
  'Nomad-Raptor-Modem-Basic-Rental-10.00': 'Nomad Raptor Modem Basic Rental $10.00',
  'Nomad-Raptor-Modem-Basic-Rental-1000': 'Nomad Raptor Modem Basic Rental $10.00 USD Monthly',
  'Nomad-Raptor-Modem-Basic-Rental-1000-USD-Monthly': 'Nomad Raptor Modem Basic Rental $10.00 USD Monthly',
  'Nomad-Raptor-Modem-Premier-Rental-25.00': 'Nomad Raptor Modem Premier Rental $25.00',
  'Nomad-Raptor-Modem-Premier-Rental-2500': 'Nomad Raptor Modem Premier Rental $25.00 USD Monthly',
  'Nomad-Raptor-Modem-Premier-Rental-2500-USD-Monthly': 'Nomad Raptor Modem Premier Rental $25.00 USD Monthly',
  'Nomad-Redemption-Fee---One-Time': 'Nomad Redemption Fee - One Time',
  'Nomad-Redemption-Fee-One-Time-USD': 'Nomad Redemption Fee - One Time USD',
  'Nomad-Residential': 'Nomad Residential',
  'Nomad-Residential-4G-Plan': 'Nomad Residential 4G Plan',
  'Nomad-Residential-4G-Plan-USD-Monthly': 'Nomad Residential 4G Plan USD Monthly',
  'Nomad-Residential-4G-Yearly': 'Nomad Residential 4G Yearly',
  'Nomad-Residential-4G-Yearly-USD-Monthly': 'Nomad Residential 4G Yearly USD Monthly',
  'Nomad-Residential-5G': 'Nomad Residential 5G',
  'Nomad-Residential-5G-USD-Monthly': 'Nomad Residential 5G USD Monthly',
  'Nomad-Residential-5G-Yearly-708': 'Nomad Residential 5G Yearly 708',
  'Nomad-Residential-5G-Yearly-708-USD-Yearly': 'Nomad Residential 5G Yearly 708 USD Yearly',
  'Nomad-Residential-5G-Yearly-850': 'Nomad Residential 5G Yearly 850',
  'Nomad-Residential-5G-Yearly-850-USD-Yearly-850': 'Nomad Residential 5G Yearly 850 USD Yearly',
  'Nomad-Residential-USD-Monthly': 'Nomad Residential USD Monthly',
  'Nomad-Rural-Power-Plan-checkout-Upfront': 'Nomad Rural Power Plan checkout Upfront',
  'Nomad-Rural-Power-Plan-checkout-Upfront-USD-Monthly': 'Nomad Rural Power Plan checkout Upfront USD Monthly',
  'Nomad-Rural-Unlimited-100-MBPS-11995': 'Nomad Rural Unlimited 100 MBPS $119.95',
  'Nomad-Rural-Unlimited-100-MBPS-11995-USD-Monthly': 'Nomad Rural Unlimited 100 MBPS $119.95 USD Monthly',
  'Nomad-Rural-Unlimited-100-Mbps-9995': 'Nomad Rural Unlimited 100 Mbps $99.95',
  'Nomad-Rural-Unlimited-100-Mbps-9995-Upfront': 'Nomad Rural Unlimited 100 Mbps $99.95 Upfront',
  'Nomad-Rural-Unlimited-100-Mbps-9995-Upfront-USD-Monthly': 'Nomad Rural Unlimited 100 Mbps $99.95 Upfront USD Monthly',
  'Nomad-Rural-Unlimited-100-Mbps-9995-USD-Monthly': 'Nomad Rural Unlimited 100 Mbps $99.95 USD Monthly',
  'Nomad-Rural-Unlimited-100-Mbps-Oasis': 'Nomad Rural Unlimited 100 Mbps Oasis',
  'Nomad-Rural-Unlimited-100-Mbps-Oasis-USD-Monthly': 'Nomad Rural Unlimited 100 Mbps Oasis USD Monthly',
  'Nomad-Rural-Unlimited-200-Mbps-9995-Upfront': 'Nomad Rural Unlimited 200 Mbps $99.95 Upfront',
  'Nomad-Rural-Unlimited-200-Mbps-9995-Upfront-USD-Monthly': 'Nomad Rural Unlimited 200 Mbps $99.95 Upfront USD Monthly',
  'Nomad-Rural-Unlimited-Ultra-200-Mbps-12995': 'Nomad Rural Unlimited Ultra 200 Mbps $129.95',
  'Nomad-Rural-Unlimited-Ultra-200-Mbps-12995-USD-Monthly': 'Nomad Rural Unlimited Ultra 200 Mbps $129.95 USD Monthly',
  'Nomad-Rural-Unlimited-Ultra-200-Mbps-14995': 'Nomad Rural Unlimited Ultra 200 Mbps $149.95',
  'Nomad-Rural-Unlimited-Ultra-200-Mbps-14995-USD-Monthly': 'Nomad Rural Unlimited Ultra 200 Mbps 149.95 USD Monthly',
  'Nomad-Rural-Unlimited-Ultra-200-Mbps-16995': 'Nomad Rural Unlimited Ultra 200 Mbps $169.95',
  'Nomad-Rural-Unlimited-Ultra-200-Mbps-16995-USD-Monthly': 'Nomad Rural Unlimited Ultra 200 Mbps $169.95 USD Monthly',
  'Nomad-Rural-Unlimited-Ultra-200-Mbps-Oasis': 'Nomad Rural Unlimited Ultra 200 Mbps Oasis',
  'Nomad-Rural-Unlimited-Ultra-200-Mbps-Oasis-USD-Monthly': 'Nomad Rural Unlimited Ultra 200 Mbps Oasis USD Monthly',
  'Nomad-SIM-Only-Unlimited-100-Mbps': 'Nomad SIM Only Unlimited 100 Mbps',
  'Nomad-SIM-Only-Unlimited-100-Mbps-USD-Monthly': 'Nomad SIM Only Unlimited 100 Mbps USD Monthly',
  'Nomad-Standard-Modem-Kit': 'Nomad Standard Modem Kit - One time Rental',
  'Nomad-Standard-Modem-Kit-USD': 'Nomad Standard Modem Kit USD - One time Rental',
  'Nomad-Stripe-Modem-Rental-0.00': 'Nomad Stripe Modem Rental $0.00',
  'Nomad-Stripe-Modem-Rental-000': 'Nomad Stripe Modem Rental $0.00 USD Monthly',
  'Nomad-Stripe-Modem-Rental-000-USD-Monthly': 'Nomad Stripe Modem Rental $0.00 USD Monthly',
  'Nomad-Travel-1995': 'Nomad Travel $9.95',
  'Nomad-Travel-1995-USD-Monthly': 'Nomad Travel $9.95 USD Monthly',
  'Nomad-Travel-Modem-Rental-15.00': 'Nomad Travel Modem Rental $15.00',
  'Nomad-Travel-Modem-Rental-1500': 'Nomad Travel Modem Rental $15.00 USD Monthly',
  'Nomad-Travel-Modem-Rental-1500-USD-Monthly': 'Nomad Travel Modem Rental $15.00 USD Monthly',
  'Nomad-Travel-Modem-Rental-with-Nomad-Premier-25.00': 'Nomad Travel Modem Rental with Nomad Premier $25.00',
  'Nomad-Travel-Modem-Rental-with-Nomad-Premier-2500': 'Nomad Travel Modem Rental with Nomad Premier $25.00 USD Monthly',
  'Nomad-Travel-Modem-Rental-with-Nomad-Premier-2500-USD-Monthly': 'Nomad Travel Modem Rental with Nomad Premier $25.00 USD Monthly',
  'Nomad-Travel-Upgrade-10.00': 'Nomad Travel Upgrade $10.00',
  'Nomad-Travel-Upgrade-1000': 'Nomad Travel Upgrade $10.00 USD Monthly',
  'Nomad-Travel-Upgrade-1000-USD-Monthly': 'Nomad Travel Upgrade $10.00 USD Monthly',
  'Nomad-Travel-Yearly-900': 'Nomad Travel Yearly 900',
  'Nomad-Travel-Yearly-900-USD-Yearly': 'Nomad Travel Yearly 900 USD Yearly',
  'Nomad-Unlimited-Base-Residential': 'Nomad Unlimited Base Residential',
  'Nomad-Unlimited-Base-Residential-USD-Monthly': 'Nomad Unlimited Base Residential USD Monthly',
  'nomad-unlimited-home': 'Nomad Unlimited Home',
  'nomad-unlimited-home-USD-Monthly': 'Nomad Unlimited Home USD Monthly',
  'Nomad-Unlimited-Light-Plan-Modem': 'Nomad Unlimited Light Plan & Modem',
  'Nomad-Unlimited-Light-Plan-Modem-USD-Monthly': 'Nomad Unlimited Light Plan & Modem USD Monthly',
  'Nomad-Unlimited-Lite-Plan': 'Nomad Unlimited Lite Plan',
  'Nomad-Unlimited-Lite-Plan-01': 'Nomad Unlimited Lite Plan Checkout',
  'Nomad-Unlimited-Lite-Plan-01-USD-Daily': 'Nomad Unlimited Lite Plan Checkout USD Daily',
  'Nomad-Unlimited-Lite-Plan-01-USD-Every-3-months': 'Nomad Unlimited Lite Plan Checkout USD Every 3 months',
  'Nomad-Unlimited-Lite-Plan-01-USD-Every-6-months': 'Nomad Unlimited Lite Plan Checkout USD Every 6 months',
  'Nomad-Unlimited-Lite-Plan-01-USD-Monthly': 'Nomad Unlimited Lite Plan 01 USD Monthly',
  'Nomad-Unlimited-Lite-Plan-01-USD-Yearly': 'Nomad Unlimited Lite Plan Checkout USD Yearly',
  'Nomad-Unlimited-Lite-Plan-Annual': 'Nomad Unlimited Lite Plan Annual Flash sales',
  'Nomad-Unlimited-Lite-Plan-Annual-USD-Yearly': 'Nomad Unlimited Lite Plan Annual USD Yearly',
  'Nomad-Unlimited-Lite-Plan-OLD': 'Nomad Unlimited Lite Plan OLD',
  'Nomad-Unlimited-Lite-Plan-OLD-USD-Every-3-months': 'Nomad Unlimited Lite Plan OLD USD Every 3 months',
  'Nomad-Unlimited-Lite-Plan-OLD-USD-Every-6-months': 'Nomad Unlimited Lite Plan OLD USD Every 6 months',
  'Nomad-Unlimited-Lite-Plan-OLD-USD-Yearly': 'Nomad Unlimited Lite Plan OLD USD Yearly',
  'Nomad-Unlimited-Lite-Plan-Paid-Upfront': 'Nomad Unlimited Lite Plan Paid Upfront',
  'Nomad-Unlimited-Lite-Plan-Paid-Upfront-USD-Every-3-months': 'Nomad Unlimited Lite Plan Paid Upfront USD Every 3 months',
  'Nomad-Unlimited-Lite-Plan-Paid-Upfront-USD-Every-6-months': 'Nomad Unlimited Lite Plan Paid Upfront USD Every 6 months',
  'Nomad-Unlimited-Lite-Plan-Paid-Upfront-USD-Monthly': 'Nomad Unlimited Lite Plan Paid Upfront USD Monthly',
  'Nomad-Unlimited-Lite-Plan-Paid-Upfront-USD-Yearly': 'Nomad Unlimited Lite Plan Paid Upfront USD Yearly',
  'Nomad-Unlimited-Lite-Plan-USD-Monthly': 'Nomad Unlimited Lite Plan USD Monthly',
  'Nomad-Unlimited-Lite-Plan-USD-Yearly': 'Nomad Unlimited Lite Plan USD Yearly',
  'Nomad-Unlimited-Power-Plan': 'Nomad Unlimited Power Plan 149.95',
  'Nomad-Unlimited-Power-Plan-30-First-Month-25-Gift-Card': 'Nomad Unlimited Travel Plan $59.95 First Month + $30 Gift Card',
  'Nomad-Unlimited-Power-Plan-30-First-Month-25-Gift-Card-USD-Monthly': 'Nomad Unlimited Travel Plan $59.95 First Month + $30 Gift Card',
  'Nomad-Unlimited-Power-Plan-9995': 'Nomad Unlimited Power Plan 99.95',
  'Nomad-Unlimited-Power-Plan-9995-USD-Monthly': 'Nomad Unlimited Power Plan 99.95 USD Monthly',
  'Nomad-Unlimited-Power-Plan-USD-Monthly': 'Nomad Unlimited Power Plan USD Monthly',
  'Nomad-Unlimited-Residential-Plan': 'Nomad Unlimited Residential Plan',
  'Nomad-Unlimited-Residential-Plan-Annual-Flash-sales': 'Nomad Unlimited Residential Plan Annual Flash sales',
  'Nomad-Unlimited-Residential-Plan-Annual-Flash-sales-USD-Yearly': 'Nomad Unlimited Residential Plan Annual Flash sales USD Yearly',
  'Nomad-Unlimited-Residential-Plan-Modem': 'Nomad Unlimited Residential Plan & Modem',
  'Nomad-Unlimited-Residential-Plan-Modem-USD-Monthly': 'Nomad Unlimited Residential Plan & Modem USD Monthly',
  'Nomad-Unlimited-Residential-Plan-USD-Monthly': 'Nomad Unlimited Residential Plan USD Monthly',
  'Nomad-Unlimited-Residential-Plan-USD-Yearly': 'Nomad Unlimited Residential Plan USD Yearly',
  'Nomad-Unlimited-Residential-PLANS': 'Nomad Unlimited Residential PLANS',
  'Nomad-Unlimited-Residential-PLANS-USD-Every-3-months': 'Nomad Unlimited Residential PLANS USD Every 3 months',
  'Nomad-Unlimited-Residential-PLANS-USD-Every-6-months': 'Nomad Unlimited Residential PLANS USD Every 6 months',
  'Nomad-Unlimited-Residential-PLANS-USD-Yearly': 'Nomad Unlimited Residential PLANS USD Yearly',
  'Nomad-Unlimited-Travel-119': 'Nomad Unlimited Travel 119',
  'Nomad-Unlimited-Travel-119-USD-Monthly': 'Nomad Unlimited Travel 119 USD Monthly',
  'Nomad-Unlimited-Travel-Plan': 'Nomad Unlimited Travel Plan',
  'Nomad-Unlimited-Travel-Plan-01': 'Nomad Unlimited Travel Plan Checkout',
  'Nomad-Unlimited-Travel-Plan-01-USD-Daily': 'Nomad Unlimited Travel Plan Checkout USD Daily',
  'Nomad-Unlimited-Travel-Plan-01-USD-Every-3-months': 'Nomad Unlimited Travel Plan Checkout USD Every 3 months',
  'Nomad-Unlimited-Travel-Plan-01-USD-Every-6-months': 'Nomad Unlimited Travel Plan Checkout USD Every 6 months',
  'Nomad-Unlimited-Travel-Plan-01-USD-Monthly': 'Nomad Unlimited Travel Plan Checkout USD Monthly',
  'Nomad-Unlimited-Travel-Plan-01-USD-Yearly': 'Nomad Unlimited Travel Plan Checkout USD Yearly',
  'Nomad-Unlimited-Travel-Plan-20-First-Month-25-Gift-Card': 'Nomad Unlimited Residential Plan $49.95 First Month + $20 Gift Card',
  'Nomad-Unlimited-Travel-Plan-20-First-Month-50-Gift-Card': 'Nomad Unlimited Residential Plan $49.95 First Month + $20 Gift Card',
  'Nomad-Unlimited-Travel-Plan-Annual-Flash-sales': 'Nomad Unlimited Travel Plan Annual Flash sales',
  'Nomad-Unlimited-Travel-Plan-Annual-Flash-sales-USD-Yearly': 'Nomad Unlimited Travel Plan Annual Flash sales USD Yearly',
  'Nomad-Unlimited-Travel-Plan-Paid-Upfront': 'Nomad Unlimited Travel Plan Paid Upfront',
  'Nomad-Unlimited-Travel-Plan-Paid-Upfront-USD-Monthly': 'Nomad Unlimited Travel Plan Paid Upfront USD Monthly',
  'Nomad-Unlimited-Travel-Plan-Paid-Upfront-USD-Yearly': 'Nomad Unlimited Travel Plan Paid Upfront USD Yearly',
  'Nomad-Unlimited-Travel-Plan-USD-Monthly': 'Nomad Unlimited Travel Plan USD Monthly',
  'Nomad-Unlimited-Travel-Plan-USD-Yearly': 'Nomad Unlimited Travel Plan USD Yearly',
  'Nomad-Unlimited-Ultra-Raptor-Plan': 'Nomad Unlimited Ultra Raptor Plan',
  'Nomad-Unlimited-Ultra-Raptor-Plan-USD-Monthly': 'Nomad Unlimited Ultra Raptor Plan USD Monthly',
  'Nomad-Wholesaler-Modem-Rental': 'Nomad Wholesaler Modem Rental',
  'Nomad-Wholesaler-Modem-Rental-USD-Monthly': 'Nomad Wholesaler Modem Rental USD Monthly',
  'Oasis--Prime-yearly-999': 'Oasis & Prime yearly $9.99 USD Yearly',
  'Oasis--Prime-yearly-999-USD-Monthly': 'Oasis & Prime yearly $9.99 USD Monthly',
  'Oasis--Prime-yearly-999-USD-Yearly': 'Oasis & Prime yearly $9.99 USD Yearly',
  'Oasis-&-Prime-yearly-9.99': 'Oasis & Prime yearly $9.99',
  'Oasis-monthly-19.95': 'Oasis monthly $19.95',
  'Oasis-monthly-1995': 'Oasis monthly $19.95 USD Monthly',
  'Oasis-monthly-1995-USD-Monthly': 'Oasis monthly $19.95 USD Monthly',
  'Redemption-Fee-Test': 'Nomad Redemption Fee',
  'Redemption-Fee-Test-USD-Daily': 'Redemption Fee USD Daily',
  'Road-Warrior': 'Road Warrior Annual',
  'Road-Warrior-USD-Yearly': 'Road Warrior Annual',
  'Sim-Card-Activation-Kit': 'Sim Card & Activation Kit',
  'Sim-Card-Activation-Kit-Annual': 'Sim Card & Activation Kit Annual',
  'Sim-Card-Activation-Kit-Annual-USD': 'Sim Card & Activation Kit Annual USD',
  'Sim-Card-Activation-Kit-USD': 'Sim Card & Activation Kit USD',
  'Standard-Modem-Kit': 'Standard Modem Kit',
  'Standard-Modem-Kit-USD': 'Standard Modem Kit USD',
  'Standard-Nomad-Modem-Kit': 'Standard Nomad Modem Kit - One time',
  'Standard-Nomad-Modem-Kit-USD': 'Standard Nomad Modem Kit USD',
  'Standard-Protection': 'Standard Protection',
  'Standard-Protection-USD': 'Standard Protection USD',
  'Test-1': 'Test $1',
  'Test-1-USD-Yearly': 'Test $1 USD Yearly',
  'Truck-Freedom': 'Truck Freedom',
  'Truck-Freedom-USD-Monthly': 'Truck Freedom Monthly',
  'Unlimited-Fixed-Wireless-Access-Business-Internet-100Mbps-Plan': 'Unlimited Fixed Wireless Access Business Internet: 100Mbps Plan',
  'Unlimited-Fixed-Wireless-Access-Business-Internet-100Mbps-Plan-USD-Monthly': 'Unlimited Fixed Wireless Access Business Internet: 100Mbps Plan USD Monthly',
  'Unlimited-Fixed-Wireless-Access-Business-Internet-200Mbps': 'Unlimited Fixed Wireless Access Business Internet: 200Mbps',
  'Unlimited-Fixed-Wireless-Access-Business-Internet-200Mbps-USD-Monthly': 'Unlimited Fixed Wireless Access Business Internet: 200Mbps USD Monthly',
  'UNLIMITED-RESIDENTIAL-PLAN': 'UNLIMITED RESIDENTIAL PLAN Checkout',
  'Unlimited-Residential-Plan-Paid-Upfront': 'Unlimited Residential Plan Paid Upfront',
  'Unlimited-Residential-Plan-Paid-Upfront-USD-Every-3-months': 'Unlimited Residential Plan Paid Upfront USD Every 3 months',
  'Unlimited-Residential-Plan-Paid-Upfront-USD-Every-6-months': 'Unlimited Residential Plan Paid Upfront USD Every 6 months',
  'Unlimited-Residential-Plan-Paid-Upfront-USD-Monthly': 'Unlimited Residential Plan Paid Upfront USD Monthly',
  'Unlimited-Residential-Plan-Paid-Upfront-USD-Yearly': 'Unlimited Residential Plan Paid Upfront USD Yearly',
  'UNLIMITED-RESIDENTIAL-PLAN-USD-Daily': 'Unlimited Residential Plan (Charged on Activation)',
  'UNLIMITED-RESIDENTIAL-PLAN-USD-Every-3-months': 'UNLIMITED RESIDENTIAL PLAN Checkout USD Every 3 months',
  'UNLIMITED-RESIDENTIAL-PLAN-USD-Every-6-months': 'UNLIMITED RESIDENTIAL PLAN Checkout USD Every 6 months',
  'UNLIMITED-RESIDENTIAL-PLAN-USD-Monthly': 'UNLIMITED RESIDENTIAL PLAN USD Monthly',
  'UNLIMITED-RESIDENTIAL-PLAN-USD-Yearly': 'UNLIMITED RESIDENTIAL PLAN Checkout USD Yearly',
  'UNLIMITED-TRAVEL-PLAN-PROMO': 'UNLIMITED TRAVEL PLAN PROMO',
  'UNLIMITED-TRAVEL-PLAN-PROMO-USD-Monthly': 'UNLIMITED TRAVEL PLAN PROMO USD Monthly',
  'Updated-Nomad-Prime-1995': 'Nomad Prime 19.95',
  'Updated-Nomad-Prime-1995-USD-Monthly': 'Nomad Prime 19.95 USD Monthly',
  'Updated-Nomad-Travel-1995': 'Nomad Travel $19.95',
  'Updated-Nomad-Travel-1995-USD-Monthly': 'Nomad Travel $19.95 USD Monthly',
  'Verizon-Red-Dragon-TBYB': 'Verizon Red Dragon TBYB',
  'Verizon-Red-Dragon-TBYB-USD-Monthly': 'Verizon Red Dragon TBYB USD Monthly',
};


export function getPlanDisplayName(planId: string): string {
  if (!planId) return 'Unknown Plan';
  
  // First, try exact match
  if (planNameMap[planId]) {
    return planNameMap[planId];
  }
  
  // Try removing USD-Period suffix for flexible matching
  let basePlanId = planId;
  const suffixPattern = /-USD-(Monthly|Yearly|Annual|Weekly|Daily|Every-6-months|Every-3-months)$/i;
  basePlanId = planId.replace(suffixPattern, '');
  
  if (planNameMap[basePlanId]) {
    return planNameMap[basePlanId];
  }
  
  // Return the original planId if no match found
  return planId;
}
